name: Build ESP32 Sketch with Custom Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: arduino-cli core install esp32:esp32@3.2.0


    - name: Unzip ESP32 core to hardware path
      run: |
        mkdir -p /home/runner/.arduino15/packages/esp32/hardware/
        unzip -q ./esp32.zip -d /home/runner/.arduino15/packages/esp32/hardware/esp32

    - name: Verify unzip contents (debug)
      run: ls -R /home/runner/.arduino15/packages/esp32/hardware/

    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 --output-dir output esp32_mod.ino
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: firmware
        path: output/esp32_mod.ino.bin
          
