name: Build ESP32 Sketch with Custom Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1


    - name: Unzip ESP32 core to hardware path
      run: |
        mkdir -p /home/runner/Arduino/hardware/espressif/esp32/
        unzip -q ./esp32.zip -d /home/runner/Arduino/hardware/espressif/esp32/

    - name: Verify unzip contents (debug)
      run: ls -R /home/runner/Arduino/hardware/

    - name: Compile sketch using custom core
      run: |
        arduino-cli compile \
          --fqbn esp32:esp32:esp32doit-devkit-v1 \
          --hardware /home/runner/Arduino/hardware \
          ./esp32_mod.ino
