name: Build Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
  

      - name: Extract ESP32 Core 3.2.0 from ZIP
        run: |
          mkdir -p $HOME/Arduino/hardware/espressif
          unzip esp32-3.2.0.zip -d $HOME/Arduino/hardware/espressif/esp32

      - name: Confirm ESP32 Core is Detected
        run: arduino-cli core list

      - name: Compile Sketch with Custom Partition
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32doit-devkit-v1 \
            --output-dir output \
            esp32_mod.ino

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/esp32_mod.ino.bin
